version: '3.8'

services:
  # Наш DWH - ClickHouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: carsharing_clickhouse
    ports:
      - "8123:8123" # HTTP интерфейс (для dbt и подключения из кода)
      - "9000:9000" # Native протокол
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - ch_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - carsharing_network
    healthcheck:
      # Проверяем, что ClickHouse готов принимать подключения
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Генератор потоковых данных на Python
  data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carsharing_generator
    restart: always
    # Подгружаем переменные из .env файла
    env_file:
      - .env
    environment:
      - CLICKHOUSE_HOST=clickhouse
    depends_on:
      clickhouse:
        condition: service_healthy # Контейнер генератора запустится ТОЛЬКО после успешного хелсчека ClickHouse
    networks:
      - carsharing_network

volumes:
  ch_data:

networks:
  carsharing_network:
    driver: bridge
