name: Data Platform CI Control

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality-and-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # ДОБАВИЛИ ОБЯЗАТЕЛЬНЫЙ ПЛАГИН ДЛЯ РАБОТЫ С DBT
        pip install sqlfluff sqlfluff-templater-dbt dbt-core dbt-clickhouse

    - name: Install dbt packages
      run: |
        cd dbt_platform
        dbt deps

    - name: Prepare dbt profile for linter
      run: cp .github/profiles.yml dbt_platform/profiles.yml

    - name: Compile dbt manifest offline
      run: |
        cd dbt_platform
        dbt compile --profiles-dir . --empty

    - name: Lint SQL via SQLFluff
      run: |
        sqlfluff lint dbt_platform/models --dialect clickhouse
