name: Data Platform CI Control

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality-and-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    # Нам нужен ТОЛЬКО сам sqlfluff. Никаких адаптеров кликхауса и dbt-core!
    - name: Install SQLFluff
      run: |
        python -m pip install --upgrade pip
        pip install sqlfluff

    # Просто запускаем линтинг текста. Никакой базы данных, никаких сетевых запросов!
    - name: Lint SQL via SQLFluff
      run: |
        sqlfluff lint dbt_platform/models --dialect clickhouse
